name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull anarbekulym/cicd_pipeline
      - name: Delete Old docker container
        run: sudo docker rm -f cicd_pipeline-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name cicd_pipeline-container anarbekulym/cicd_pipeline